### ISSUE TITLE
platformShowToastEvent mock is missing export

### ISSUE THREAD

**Issue by marktuk** [salesforce/lwc-jest#58]
`lwc-recipes` use the `ShowToastEventName` variable to create event listeners for testing toasts. The export is missing from the mock implementation in `lwc-jest`. 

https://github.com/salesforce/lwc-jest/blob/master/src/lightning-stubs/platformShowToastEvent/platformShowToastEvent.js

Additionally, the event name `lightning__showtoast` seems to generate a LWC warning:

```
    console.warn node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:208
      [LWC warning]: Invalid event type "lightning__showtoast" dispatched in element <c-toaster>. Event name should only contain 
lowercase alphanumeric characters.
```

**Comment by trevor-bliss** [comment]
`lwc-recipes` actually overrides the `platformShowToastEvent` stub to use their own that exports the `ShowToastEventName` value: https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/test/jest-mocks/lightning/platformShowToastEvent.js#L7

The reason we don't export that value for the default stub here is because the real implementation of platformShowToastEvent does not export it. The purpose of these stubs is to mimic the API of the real base components/libraries and provide some shell implementation, but leave the ability to override the defaults.
