### ISSUE TITLE
Remove API version check

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc-jest#60]
`lwc-jest` checks currently hardcoded for the API version of the current project (see [here](https://github.com/salesforce/lwc-jest/blob/0129287e07db4b45b1a7cc2aadfa1b7f49ff9038/src/config.js#L42)). This breaks unit testing capabilities for projects that are already working on Summer '19 projects with API version `46.0`.

As LWC and with that Jest is only relevant from v45 upwards, and wouldn't even deploy LWCs, we can IMHO remove this check.

**Comment by trevor-bliss** [comment]
If you're testing against Summer '19 then you should be on the `prerelease` branch, which is npm version 0.5.0. This is because Summer '19 is still only available in sandbox orgs. Once Summer '19 is released to production instances we will merge `prerelease` with master.

The reason for all of this is because `lwc-jest` has a direct dependency on LWC which needs to be kept in sync with what is in the production orgs.

I'll update the README to highlight this.
